# Generated by Django 6.0.7 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(default="USER", max_length=11)),
                (
                    "company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="A", max_length=1)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "USER"},
        ),
    ]
