# Generated by Django 6.0.7 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureGroup",
            fields=[
                (
                    "feature_group_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("feature", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "BDM_FEATURE_GROUP",
                "ordering": ("feature_group_id",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureType",
            fields=[
                (
                    "feature_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("feature", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "feature_group",
                    models.ForeignKey(
                        db_column="feature_group_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="feature_types",
                        to="accounts.featuregroup",
                    ),
                ),
            ],
            options={
                "db_table": "BDM_FEATURE_TYPE",
                "ordering": ("feature_type_id",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "feature_value_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "feature_type_name",
                    models.CharField(
                        db_column="feature_type",
                        max_length=255,
                    ),
                ),
                ("feature", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "c_weight",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "s_weight",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "o_weight",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "feature_group",
                    models.ForeignKey(
                        db_column="feature_group_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="feature_values",
                        to="accounts.featuregroup",
                    ),
                ),
                (
                    "feature_type",
                    models.ForeignKey(
                        db_column="feature_type_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="feature_values",
                        to="accounts.featuretype",
                    ),
                ),
            ],
            options={
                "db_table": "BDM_FEATURE_VALUE",
                "ordering": ("feature_value_id",),
                "managed": False,
            },
        ),
    ]
