# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_company_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretype",
            name="physical_type",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="featuretype",
            name="semantic_role",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImageReference",
            fields=[
                ("company_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                (
                    "image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("image_origin_name", models.CharField(max_length=255)),
                ("image_name", models.CharField(max_length=255)),
                ("image_path", models.CharField(max_length=255)),
                (
                    "use_yn",
                    models.CharField(default="Y", max_length=1),
                ),
                ("regist_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "feature_value",
                    models.ForeignKey(
                        db_column="feature_value_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="image_references",
                        to="accounts.featurevalue",
                    ),
                ),
            ],
            options={
                "db_table": "BDM_IMAGE_REFERENCE",
                "ordering": ("-regist_date", "-image_id"),
                "managed": False,
            },
        ),
    ]
