# Generated by Django 6.0.7 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_feature_type_image_fields_and_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cso_classification", models.CharField(max_length=16)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ordering_agency",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "body_file_path",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "other_file_paths",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ("-production_date", "-id"),
                "managed": False,
            },
        ),
    ]
